apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echoserver-v1
  name: echoserver-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-v1
  template:
    metadata:
      labels:
        app: echoserver-v1
      annotations:
        dev.mesh.nocalhost.dev: "true"
        dev.mesh.nocalhost.dev/uuid: "ca0b6df5"
        dev.mesh.nocalhost.dev/type: "origin"
    spec:
      containers:
        - image: nocalhost-docker.pkg.coding.net/fake/images/echoserver:1.13.3
          name: echoserver
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: version
              value: v1
        - args:
            - envoy
            - -c
            - /etc/envoy/envoy.yaml
            - -l
            - trace
            - --service-node
            - "$(POD_NAME)"
          image: naison/envoy:v1.21.0-with-iptables
          imagePullPolicy: Always
          name: envoy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          securityContext:
            privileged: true
